### ISSUE TITLE
Fix some issues in stdhep tools

### ISSUE THREAD

**Issue by tongtongcao** [JeffersonLab/hps-mc#143]

**Comment by JeremyMcCormick** [comment]
More info?

**Comment by tongtongcao** [comment]
Here is a report to explain issues and solutions for this issue branch:
https://confluence.slac.stanford.edu/display/hpsg/2019.12.10+--+Software+Meeting?preview=/269127366/269127691/Issues%20and%20solutions%20issued%20and%20solutions%20for%20stdhep%20tools.pdf

1) Found a memory leak in the stdhep tools. This was causing issues running on large files.
2) Issue with file open not returning the number of events properly.
3) Use of random_sample.cc - 
          i) Need to produce more events than N for random sampling. 
          ii) random_sample.cc reads in all the input into a vector. This takes a lot of memory.
          iii) random_sample.cc picks the input events at random. This means that an estimate of 37% input events are not used, and 37% are used more than once.
                    a) Solution1: random_sample_usingInputEventsInOrder.cc  – Just takes the events in order, avoiding the memory issue and the usage issue.
                    b) Solution2: Update of random_sample.cc  – Use the std::shuffle to randomize the order of the events. No waste of electrons, and less memory use.

**Comment by tongtongcao** [comment]
> More info?

Here is a report to explain issues and solutions for this issue branch:
https://confluence.slac.stanford.edu/display/hpsg/2019.12.10+--+Software+Meeting?preview=/269127366/269127691/Issues%20and%20solutions%20issued%20and%20solutions%20for%20stdhep%20tools.pdf

Found a memory leak in the stdhep tools. This was causing issues running on large files.
Issue with file open not returning the number of events properly.
Use of random_sample.cc -
i) Need to produce more events than N for random sampling.
ii) random_sample.cc reads in all the input into a vector. This takes a lot of memory.
iii) random_sample.cc picks the input events at random. This means that an estimate of 37% input events are not used, and 37% are used more than once.
a) Solution1: random_sample_usingInputEventsInOrder.cc – Just takes the events in order, avoiding the memory issue and the usage issue.
b) Solution2: Update of random_sample.cc – Use the std::shuffle to randomize the order of the events. No waste of electrons, and less memory use.

**Comment by JeremyMcCormick** [comment]
@tongtongcao Says this is resolved.
