### ISSUE TITLE
updates for stdhep tool and EGS5 programs and lhe readers

### ISSUE THREAD

**Issue by tongtongcao** [JeffersonLab/hps-mc#165]

**Comment by tongtongcao** [comment]
ESG5 programs:
- lhe_rad.f: program for RAD smaple
- lhe_prompt.f: program for ap prompt sample
- llhe_exponential.f: program for ap displaced sample with "exponential-decay" model
- lhe_uniform.f: program for ap displaced sample with "uniform-decay" model

stdhep_tools: add_mother_update2.cc
Parent particles for final-state particles from EGS5 output are added into events so that fully truth information can be included in the final data sample.

**Comment by JeremyMcCormick** [comment]
This is obsolete now.
