### ISSUE TITLE
Updates for egs5 programs

### ISSUE THREAD

**Issue by tongtongcao** [JeffersonLab/hps-mc#171]
ESG5 programs are updated by Takashi:
- lhe_rad.f: program for RAD smaple
- lhe_prompt.f: program for ap prompt sample
- llhe_exponential.f: program for ap displaced sample with "exponential-decay" model
- lhe_uniform.f: program for ap displaced sample with "uniform-decay" model

**Comment by JeremyMcCormick** [comment]
This was resolved by #172
