### ISSUE TITLE
New job and example for full chain testing

### ISSUE THREAD

**Issue by cbravo135** [JeffersonLab/hps-mc#241]
We should add a new job type which generates a small amount of tritrig_beam from gen of everything all the way to the final recon file. This job would test pretty much all the most important job components in hpsmc for making a sample, but just make maybe only 1000 events or so. We would want it to be big enough to have at least a handful of triggered tritrig+beam events in the end.

**Comment by JeremyMcCormick** [comment]
plots from anaVtxTuple_cfg.py in hpstr

**Comment by JeremyMcCormick** [comment]
Several examples do this already (minus beam gen).
