### ISSUE TITLE
Fix hard-coded paths in examples

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-mc#261]
Many examples have hard-coded paths which not generally be necessary. Directories and other files should be relative to the example's base dir.

For example, run scripts should look like this:

```
hps-mc-job run -d $PWD/scratch tritrig job.json
```

There is still not a production area in use, where hard-coded paths based on the site (SLAC or JLAB) would make more sense.

**Comment by sarahgaiser** [comment]
This has been done with my prior work on hps-mc/examples
