### ISSUE TITLE
Seeds not set properly for Geant4

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-mc#275]
Need two seeds rather than one:

```/random/setSeeds 8904138 1546569```

I am not sure what behavior we are getting by only setting a single seed in SLIC.

**Comment by tomeichlersmith** [comment]
The behavior depends on [which random number generator](https://geant4-userdoc.web.cern.ch/UsersGuides/ForApplicationDeveloper/BackupVersions/V10.7/html/Fundamentals/global.html#heprandom-engines) you are using in SLIC. I believe the default is HepJamesRandom (which I think does require two seeds).

Without modification within SLIC, the `/random/setSeeds` macro command is handled by [G4RunMessenger](https://apc.u-paris.fr/~franco/g4doxy/html/classG4RunMessenger.html) which simply provides the list of integers to `CLHEP::HepRandom::setTheSeeds` as an array of `long`s.
