### ISSUE TITLE
Make GSL configuration easier

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-mc#382]
Currently, GSL config in CMake requires something like:

```
-DGSL_INCLUDE_DIR=${gsl_dir}/include \
-DGSL_LIBRARY=${gsl_dir}/lib/libgsl.so \
-DGSL_CBLAS_LIBRARY=${gsl_dir}/lib/libgslcblas.so
```

This could be improved by setting these automatically if the user supplies a single `GSL_DIR` argument to CMake.

**Comment by tomeichlersmith** [comment]
You can use the parameter `GSL_ROOT_DIR` to achieve this.

```
  -DGSL_ROOT_DIR=${gsl_dir}
```

This is the default behavior of CMake's find_package and is documented in the README.

https://github.com/JeffersonLab/hps-mc/blob/6b142756a956c054538688ffae06b68194b86824/README.md?plain=1#L33-L51

**Comment by JeremyMcCormick** [comment]
Okay, thanks. I'll verify and then close this if it works....

**Comment by JeremyMcCormick** [comment]
> You can use the parameter `GSL_ROOT_DIR` to achieve this.
> 
> ```
>   -DGSL_ROOT_DIR=${gsl_dir}
> ```
> 
> This is the default behavior of CMake's find_package and is documented in the README.
> 
> https://github.com/JeffersonLab/hps-mc/blob/6b142756a956c054538688ffae06b68194b86824/README.md?plain=1#L33-L51

This works fine. 

Thanks @tomeichlersmith
